DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS auto;
DROP TABLE IF EXISTS lenguaje;
DROP TABLE IF EXISTS marca;
DROP TABLE IF EXISTS paise;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS provincia_localidad;

commit